[project]
name = "haversine"
version = "0.1.0"
description = "Generates Haversine points and calculates pair distances."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "numpy>=2.3.3",
]


[project.scripts]
gendata = "gendata:main"
